### ISSUE TITLE
Animations on Social Media Icons

### ISSUE THREAD

**Issue by liy4502** [dchopra001/Dym_hrk#10]
One of her requirement was social media icons on the top left corner with zoom in and out animation. We will use Animate.css and Font Awesome for this

**Comment by liy4502** [comment]
By using animate.css library and font-awesome

Include this in the header
<link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />

We specify the icon is **fa fa-facebook-square**
We specify the animation is  **animated pulse infinite**
We add link on click and remove under for mouseover with the css 
<a href="xxxxx" target="_blank"><i id="social_media_icons" class="fa fa-facebook-square animated pulse infinite" aria-hidden="true"></i>&nbsp;</a>

a:link {
+    text-decoration: none;
+}
+
+a:visited {
+    text-decoration: none;
+}
+
+a:hover {
+    text-decoration: none;
+}
+
+a:active {
+    text-decoration: none;
+}

**Comment by dchopra001** [comment]
why was this closed?

**Comment by liy4502** [comment]
I added these animations by using font awesome and animate.css.
class = fa fa-facebook-square adds the facebook social media icon through font awesome.
class = animate pulse infinite animates anything within the class to have a pulsing animation. Infinite repeats the animation.

id = social_media_icons is contained in the Images.css page. This id stylizes the class to have a certain color and font size.

Lastly I changed links to not underline when you mouse over or click on the link.

a:visited {
text-decoration: none;
}

**Comment by dchopra001** [comment]
Was the PR merged? Also can you put a link for it here so it's easy to reference in the future?

**Comment by liy4502** [comment]
No the PR is not merged, but I have tested this in different browsers and its working.
[https://github.com/dchopra001/Dym_hrk/pull/12](url)

**Comment by dchopra001** [comment]
cool thanks!
